/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eoss.search;

import eoss.model.Design;
import eoss.model.DesignSpace;

import java.util.ArrayList;

public class App {

    public static void main(String[] args) {


        ArrayList<String> instruments = new ArrayList<>();
        instruments.add("VIIRS");
        instruments.add("BIOMASS");
        instruments.add("SMAP_MWR");
        instruments.add("SMAP_RAD");
        instruments.add("CMIS");

        DesignSpace design_space = new DesignSpace(instruments);
        Design design = new Design(design_space);
        design.print();






    }
}
